name: Deploy to ShinyApps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install setuptools and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install rsconnect-python
      run: |
        pip install rsconnect-python

    - name: Add rsconnect account
      run: |
        rsconnect add --account ${{ secrets.RS_CONNECT_ACCOUNT }} --name ${{ secrets.RS_CONNECT_NAME }} --token ${{ secrets.RS_CONNECT_TOKEN }} --secret ${{ secrets.RS_CONNECT_SECRET }}

    - name: Deploy to ShinyApps.io
      run: |
        rsconnect deploy shiny . --name ${{ secrets.RS_CONNECT_NAME }} --title shiny --force
