name: Deploy to ShinyApps.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install setuptools and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install rsconnect-python
      run: |
        pip install rsconnect-python

    - name: Retrieve Firebase key
      run: |
        echo "$FIREBASE_KEY" > firebase_key.json
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        
    - name: Delete existing app
      env:
        RS_CONNECT_TOKEN: ${{ secrets.RS_CONNECT_TOKEN }}
        RS_CONNECT_SECRET: ${{ secrets.RS_CONNECT_SECRET }}
      run: |
        rsconnect add --account ${{ secrets.RS_CONNECT_ACCOUNT }} --name ${{ secrets.RS_CONNECT_NAME }} --token ${{ secrets.RS_CONNECT_TOKEN }} --secret ${{ secrets.RS_CONNECT_SECRET }}
        rsconnect remove shiny --name ${{ secrets.RS_CONNECT_NAME }} --account ${{ secrets.RS_CONNECT_ACCOUNT }} || true

    - name: Deploy to ShinyApps.io
      env:
        RS_CONNECT_TOKEN: ${{ secrets.RS_CONNECT_TOKEN }}
        RS_CONNECT_SECRET: ${{ secrets.RS_CONNECT_SECRET }}
      run: |
        rsconnect add --account ${{ secrets.RS_CONNECT_ACCOUNT }} --name ${{ secrets.RS_CONNECT_NAME }} --token ${{ secrets.RS_CONNECT_TOKEN }} --secret ${{ secrets.RS_CONNECT_SECRET }}
        rsconnect deploy shiny . --name ${{ secrets.RS_CONNECT_NAME }} --title shiny