name: Deploy to ShinyApps

on:
  push:
    branches:
      - main  # or the branch you use for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install rsconnect

      - name: Deploy to ShinyApps.io
        env:
          RS_CONNECT_ACCOUNT: ${{ secrets.RS_CONNECT_ACCOUNT }}
          RS_CONNECT_NAME: ${{ secrets.RS_CONNECT_NAME }}
          RS_CONNECT_TOKEN: ${{ secrets.RS_CONNECT_TOKEN }}
          RS_CONNECT_SECRET: ${{ secrets.RS_CONNECT_SECRET }}
        run: |
          rsconnect add --account $RS_CONNECT_ACCOUNT --name $RS_CONNECT_NAME --token $RS_CONNECT_TOKEN --secret $RS_CONNECT_SECRET
          rsconnect deploy shinyapps --app-dir .
